
m1 = Movie.create(title: "2012", image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/dd/2012_Poster.jpg/220px-2012_Poster.jpg", release_year: "2009", plot: "In 2009, American geologist Adrian Helmsley visits astrophysicist Satnam Tsurutani in India and learns that an exotic new type of neutrinos from a huge solar flare are heating Earth's core. In Washington, D.C., Helmsley presents his information to White.......")
m2 = Movie.create(title: "Miss Congeniality", image: "https://upload.wikimedia.org/wikipedia/en/f/f6/Miss_Congeniality_Poster.jpg", release_year: "2000", plot: "Gracie is now a tough Special Agent for the FBI. During a sting operation against Russian mobsters, she disobeys her superior's orders in order to save a mob boss who appears to be choking, which causes one of the other agents to be shot. She is ........")
m3 = Movie.create(title: "Rush Hour", image: "https://upload.wikimedia.org/wikipedia/en/thumb/4/49/Rush_Hour_poster.png/220px-Rush_Hour_poster.png", release_year: "1998", plot: "On the last day of British rule of Hong Kong in 1997, Detective Inspector Lee of the Hong Kong Police Force leads a raid at the wharf, hoping to arrest the unidentified, anonymous crime lord Juntao.")
m4 = Movie.create(title: "Fast and Furious 9", image: "https://upload.wikimedia.org/wikipedia/en/2/2b/F9_film_poster.jpg", release_year: "2021", plot: "In 1989, Jack Toretto participates in a race, with his sons Dominic and Jakob in his pit crew. Dom argues with rival racer Kenny Linder about his dirty tactics. As the race resumes, Linder's car clips Jack's bumper....")
m5 = Movie.create(title: "A Quite Place 2", image: "https://upload.wikimedia.org/wikipedia/en/thumb/0/02/A_Quiet_Place_Part_II.jpg/220px-A_Quiet_Place_Part_II.jpg", release_year: "2020", plot: "During a baseball game the Abbott family is attending, spectators witness a strange cloud-like object hurtle towards the Earth. As people quickly exit the park and attempt to drive away, hostile alien creatures attack the town. The blind creatures possess....")
m6 = Movie.create(title: "Jungle Cruise", image: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c6/Jungle_Cruise_-_theatrical_poster.png/220px-Jungle_Cruise_-_theatrical_poster.png", release_year: "2021", plot: "In the 16th century, Don Aguirre leads Spanish conquistadors to South America to search for the Tears of the Moon, a mythical tree whose petals can cure any illness, heal all injuries, and lift every curse.")
m7 = Movie.create(title: "Iron Man", image: "https://content.codecademy.com/courses/learn-rails/img/iron-man.jpg", release_year: "2008", plot: "A billionaire industrialist and genius inventor, Tony Stark (Robert Downey Jr.), is conducting weapons tests overseas, but terrorists kid...")
m8 = Movie.create(title: "Spiderman Home-Coming", image: "https://upload.wikimedia.org/wikipedia/en/f/f9/Spider-Man_Homecoming_poster.jpg", release_year: "2017", plot: "Following the Battle of New York,[N 1] Adrian Toomes and his salvage company are contracted to clean up the city, but their operation is taken over by the Department of Damage Control (DODC), a partnership between Tony Stark and the U.S. government.")
m9 = Movie.create(title: "Captain Marvel", image: "https://upload.wikimedia.org/wikipedia/en/4/4e/Captain_Marvel_%28film%29_poster.jpg", release_year: "2019", plot: "In 1995, on the Kree Empire's capital planet of Hala, Starforce member Vers suffers from amnesia and recurring nightmares involving an older woman. Yon-Rogg, her mentor and commander, trains Vers to control her abilities, while the Supreme Intelligence, the artificial intelligence that rules the Kree...")
m10 = Movie.create(title: "The Avengers", image: "https://upload.wikimedia.org/wikipedia/en/8/8a/The_Avengers_%282012_film%29_poster.jpg", release_year: "2018", plot: "In 2018, twenty-three days after Thanos killed half of all life in the universe, Carol Danvers rescues Tony Stark and Nebula from deep space and they reunite with the remaining Avengers—Bruce Banner, Steve Rogers, Thor, Natasha Romanoff, and James Rhodes—and Rocket on Earth.")

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
